---
title: "03.CRPCholCalpro"
author: "Kelsey Huus"
date: "2024-07-29"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
##Packages
library(dplyr)
library(ggplot2)
#library(data.table)
library(tidyr)
```

```{r metadata}
#per-sample metadata #note: mocks, blanks & samples with low read depth already excluded #so are old & infected samples
#updated: this version also excludes SERIES 2 of all double series.
meta_seq <- read.csv("/ebio/abt3_projects2/uHEAT/data/metadata/meta_seq_clean_series1.24.08.18.csv", 
                     row.names=1)
meta_seq$fever7d_aboveavg <- factor(meta_seq$fever7d_aboveavg, levels=c("lo", "hi"))

#per-person metadata, matching
meta <- meta_seq %>% filter(!duplicated(Participant_ID)&!is.na(fever7d_aboveavg)) %>%
  dplyr::select(-c(SampleID, Relative_Day, Time0, Time01))
dim(meta)

#define DIET 3
meta$Diet3 <- ifelse(meta$Diet %in% c("Vegan", "Vegetarian"), yes="Veg", no="Omni")
meta_seq$Diet3 <- ifelse(meta_seq$Diet %in% c("Vegan", "Vegetarian"), yes="Veg", no="Omni")


```

```{r Calprotectin ELISA}

lc <- read.csv("/ebio/abt3_projects2/uHEAT/data/metadata/LCN2.Calpro.ELISA.Interpolations.csv")
head(lc)
#multiple both LCN2 and Calpro by 20 for dilution factor 
#note that where the factor is different (plate 5) due to a 1:10 instead of 1:20 dilution, this is already manually adjusted by 1/2 in the excel sheet
lc$LCN2 <- lc$LCN2*20
lc$Calpro <- lc$Calpro*20
#for the few duplicates, take an average per participant 
lc$Participant_ID <- sapply(strsplit(lc$SampleID,"_"), `[`, 1)
lc$Participant_ID <- gsub("H", "HEAT_", lc$Participant_ID)
lc <- lc %>% group_by(Participant_ID) %>%
  summarize(LCN2.pg.mL=mean(LCN2, na.rm=TRUE),
            Calpro.pg.mL=mean(Calpro, na.rm=TRUE))
lc <- lc %>% filter(Participant_ID!="BLANK")
lc

lc_meta <- full_join(lc, meta)

wilcox.test(lc_meta$LCN2.pg.mL~lc_meta$fever7d_aboveavg)
wilcox.test(lc_meta$Calpro.pg.mL~lc_meta$fever7d_aboveavg) #p=0.0016

pdata <- lc_meta %>% filter(!is.na(fever7d_aboveavg))
pdata$fever7d_aboveavg <- factor(pdata$fever7d_aboveavg, levels=c("lo", "hi"))

cairo_pdf(width=3, height=3, "/ebio/abt3_projects2/uHEAT/data/CleanPlots/2D.Calpro.pdf")
p <- ggplot(pdata, aes(x=fever7d_aboveavg, y=log(Calpro.pg.mL), colour=fever7d_aboveavg)) + geom_boxplot(outlier.shape=NA) + geom_jitter(width=0.1, height=0) + 
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
               panel.background = element_blank(), axis.line = element_line(colour = "black"),
               axis.title.y = element_text(margin = margin(r = 10))) +
  scale_colour_manual(values=c("grey50", "firebrick3")) + 
  annotate("segment", x=1, xend=2, y=12.25, yend=12.25) + 
  annotate("text", label=c("**"), x=1.5, y=12.5, size=5) + 
  ylab("Fecal Calprotectin (pg/mL)") + xlab("∆T") + theme(legend.position = "none")
p 
dev.off()

#comparing clinical units of calpro
#note for clinical measuremnts it would normally be expressed as µg per mg of stool #all stool at 0.2 g /mL
lc_meta$Calpro.pg.g <- lc_meta$Calpro.pg.mL/200 #1 mL per 200 mg
lc_meta$Calpro.µg.g <- lc_meta$Calpro.pg.g / 1000 / 1000 #pg to ng to µg 
summary(lc_meta$Calpro.µg.g) #this seems low now that the units are I think correct.
summary(lc_meta$Calpro.pg.g)

lc <- lc %>% filter(!is.na(Calpro.pg.mL))

#export for supplementary table
lc_export <- lc_meta %>% filter(!is.na(Calpro.pg.mL) & !is.na(fever7d_aboveavg)) %>%
  dplyr::select(Participant_ID, Calpro.pg.mL, Calpro.µg.g) 
dim(lc_export)

#write.csv(lc_export, "/ebio/abt3_projects2/uHEAT/data/SupplementalTables/S#_Calpro.csv")

```

```{r calprotectin NEW qpcr tidy code}
calpro <- read.csv("/ebio/abt3_projects2/uHEAT/data/metadata/HumanCalpro_FecalFoldChangesPercDNABatch_R.csv")
calpro

calpro$cDNA_Batch <- sapply(strsplit(as.character(calpro$Batch), ".", fixed=TRUE), `[`, 1)

#is there a batch effect? #batch effect is removed if I normalize CT values per plate/cDNA instead of overall
ggplot(calpro, aes(x=as.factor(Batch), y=log(FoldChange))) + geom_boxplot(outlier.shape=NA) + geom_jitter(width=0.1, height=0)
kruskal.test(FoldChange~as.factor(Batch), data=calpro) #no batch effect

ggplot(calpro, aes(x=as.factor(cDNA_Batch), y=log(FoldChange))) + geom_boxplot(outlier.shape=NA) + geom_jitter(width=0.1, height=0)
kruskal.test(FoldChange~as.factor(cDNA_Batch), data=calpro) #analyzed by cDNA batch it is very normal

#which batch are the technical duplicates in?
calpro_dups <- calpro %>% filter(duplicated(SampleID))
calpro_dups <- calpro %>% filter(SampleID %in% calpro_dups$SampleID)

#take the 'first' duplicates from batch 0 because I'm already sure that these ones correspond well with the ELISA data.
calpro <- calpro %>% filter(!(SampleID %in% calpro_dups$SampleID & Batch!=0)) #exclude dups other than batch 0
dim(calpro) #313 samples #now it's 361

#exclude samples with non-detection (CT==40 for both technical replicates) in GAPDH, S100A9, or both
#make sure the flags are definitely correct (I did them manually first) by redefining them in R
calpro$ND_FLAG_G <- ifelse(calpro$CT1_G==40.00&calpro$CT2_G==40.00, "G", "")
calpro$ND_FLAG_S <- ifelse(calpro$CT1_S==40.00&calpro$CT2_S==40.00, "S", "")
calpro$ND_FLAG_r <- paste(calpro$ND_FLAG_G, calpro$ND_FLAG_S, sep="")
identical(calpro$ND_FLAG, calpro$ND_FLAG_r) #not true!
calpro %>% filter(ND_FLAG!=ND_FLAG_r) #now there is only one left, and it should be real exclude (because of NA)

calpro_filt <- calpro %>% filter(!(ND_FLAG%in%c("GS", "G")))
dim(calpro_filt) #351, excludes 10 samples #or 305, excludes >50 #new samples, n=395

#associate with meta
calpro_meta <- full_join(calpro_filt, meta_seq) %>% filter(!is.na(FoldChange) & !is.na(Participant_ID))
length(calpro_meta$SampleID) #281 valid samples #now 329 #or 319, etc. based on filtering
dplyr::count(calpro_meta, Participant_ID) #from 47 people #now 95 #or 94 etc. based on filtering
length(as.data.frame(dplyr::count(calpro_meta, Participant_ID))$n) #n=136 participants now

#plot and test the sample 3's only.
calpro_3 <- calpro_meta %>% filter(sample_no==3) #no joining with ELISA data. Avoid confusion.
dim(calpro_3) #95 people as expected #updated: n=134 #now: n=145

summary(calpro_3$FoldChange) #exclude craaazy fold changes over 100 or less than 0.00000? (ie 10x highest quartile or 10x lowest)
calpro_3_filt <- calpro_3 %>% filter(!(FoldChange>100)&!(FoldChange<0.000001))
dim(calpro_3_filt) #n=137 people
wilcox.test(calpro_3_filt$FoldChange ~ calpro_3_filt$fever7d_aboveavg) #p=0.08 :) 

#cairo_pdf(width=3, height=3, "/ebio/abt3_projects2/uHEAT/data/CleanPlots/Fig2E_Calpro_fever7d_qPCR.pdf")
p <- ggplot(calpro_3_filt, aes(x=fever7d_aboveavg, y=log(FoldChange), colour=fever7d_aboveavg)) +
  geom_boxplot(outlier.shape=NA) +
  geom_jitter(width=0.1, height=0) +
    scale_colour_manual(values=c("grey60", "firebrick3")) +
  annotate('segment', x=1, xend=2, y=7.2, yend=7.2) +
  annotate('text', x=1.5, y=8, label=c("p=0.08")) +
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
               panel.background = element_blank(), axis.line = element_line(colour = "black"),
               axis.title.y = element_text(margin = margin(r = 10))) +
  ylab("S100A9 (Log Fold Change)") + xlab("∆T") + theme(legend.position = "none") 
p
#dev.off()

#check over time.
#don't take all the sample 3's for this one, i.e. only participants with more than one time point
pdata <- calpro_meta %>% filter(!(cDNA_Batch %in% c("4", "5", "6")))

#cairo_pdf(width=4, height=3, "/ebio/abt3_projects2/uHEAT/data/CleanPlots/3I_Calpro_Time01.pdf")
p <- ggplot(pdata, aes(x=Time01, y=log(FoldChange), colour=fever7d_aboveavg)) + 
  #geom_point() + 
  geom_line(aes(group=Participant_ID), alpha=0.3) +
  geom_smooth(method='loess', fill='white', alpha=0.7) + 
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
               panel.background = element_blank(), axis.line = element_line(colour = "black"),
               axis.title.y = element_text(margin = margin(r = 10))) + 
  xlab("Time (days)") + ylab("Log Fold Change") + 
  ggtitle("S100A9") + labs(colour="∆T") + 
  scale_x_continuous(breaks = (seq(-7, 7, by = 7))) + 
  scale_colour_manual(values=c("grey50", "firebrick3")) +
  annotate('segment', x=0, xend=0, y=-3, yend=6, linetype='dashed')
p
#dev.off()

#test statistically via mixed linear model #the same way as for beta diversity 
m1 <- lme(FoldChange ~ seq_depth +  Bristol_Stool_Score2 + Time01 + fever7d_aboveavg + Time01*fever7d_aboveavg, random=~1|Participant_ID, data = pdata, 
            na.action=na.exclude, method="ML")
summary(m1) #NS

```


```{r calprotectin NEW qpcr}
calpro <- read.csv("/ebio/abt3_projects2/uHEAT/data/metadata/HumanCalpro_FecalFoldChangesPercDNABatch_R.csv")
calpro

calpro$cDNA_Batch <- sapply(strsplit(as.character(calpro$Batch), ".", fixed=TRUE), `[`, 1)

#is there a batch effect? #batch effect is removed if I normalize CT values per plate/cDNA instead of overall
ggplot(calpro, aes(x=as.factor(Batch), y=log(FoldChange))) + geom_boxplot(outlier.shape=NA) + geom_jitter(width=0.1, height=0)
kruskal.test(FoldChange~as.factor(Batch), data=calpro) #no batch effect

ggplot(calpro, aes(x=as.factor(cDNA_Batch), y=log(FoldChange))) + geom_boxplot(outlier.shape=NA) + geom_jitter(width=0.1, height=0)
kruskal.test(FoldChange~as.factor(cDNA_Batch), data=calpro) #analyzed by cDNA batch it is very normal

#which batch are the technical duplicates in?
calpro_dups <- calpro %>% filter(duplicated(SampleID))
calpro_dups <- calpro %>% filter(SampleID %in% calpro_dups$SampleID)

#how well do the dups correlate?
calpro_dups_plot <- calpro_dups %>% select(SampleID, FoldChange, cDNA_Batch) %>%
  pivot_wider(names_from=cDNA_Batch, values_from=FoldChange)
calpro_dups_plot$replicate <- ifelse(!is.na(calpro_dups_plot$`1`), 
                                     calpro_dups_plot$`1`,
                                     calpro_dups_plot$`2`)
calpro_dups_plot
p <- ggplot(calpro_dups_plot, aes(x=log(`0`), y=log(replicate))) + geom_point() + geom_smooth(method='lm')
p #not bad, not great
p <- ggplot(calpro_dups_plot, aes(x=log(`0`), y=log(`1`))) + geom_point() + geom_smooth(method='lm')
p #better (cDNA batch 1)
p <- ggplot(calpro_dups_plot, aes(x=log(`0`), y=log(`2`))) + geom_point() + geom_smooth(method='lm')
p #worse (cDNA batch 2)

#take the 'first' duplicates from batch 0 because I'm already sure that these ones correspond well with the ELISA data.
calpro <- calpro %>% filter(!(SampleID %in% calpro_dups$SampleID & Batch!=0)) #exclude dups other than batch 0
dim(calpro) #313 samples #now it's 361

#exclude samples with non-detection (CT==40 for both technical replicates) in GAPDH, S100A9, or both
#make sure the flags are definitely correct (I did them manually first) by redefining them in R
calpro$ND_FLAG_G <- ifelse(calpro$CT1_G==40.00&calpro$CT2_G==40.00, "G", "")
calpro$ND_FLAG_S <- ifelse(calpro$CT1_S==40.00&calpro$CT2_S==40.00, "S", "")
calpro$ND_FLAG_r <- paste(calpro$ND_FLAG_G, calpro$ND_FLAG_S, sep="")
identical(calpro$ND_FLAG, calpro$ND_FLAG_r) #not true!
calpro %>% filter(ND_FLAG!=ND_FLAG_r) #now there is only one left, and it should be real exclude (because of NA)

calpro_filt <- calpro %>% filter(!(ND_FLAG%in%c("GS", "G")))
dim(calpro_filt) #351, excludes 10 samples #or 305, excludes >50 #new samples, n=395

#what about a further QC on any non-detectable technical replicates
#calpro_filt$CT2_G <- as.numeric(calpro_filt$CT2_G)
#calpro_filt$CT_flag_G <- ifelse(calpro_filt$CT1_G==40.00 | calpro_filt$CT2_G==40.00, yes="FLAG", no="")
#calpro_filt$CT_flag_S <- ifelse(calpro_filt$CT1_S==40.00 | calpro_filt$CT2_S==40.00, yes="FLAG", no="")

#calpro_filt2 <- calpro_filt %>% filter(CT_flag_G!="FLAG") #got rid of a few additional samples, n=313

#calpro_filt2 <- calpro_filt %>% filter(CT_flag_G!="FLAG"&CT_flag_S!="FLAG")
#dim(calpro_filt2) #n=256 samples now

#what about a further QC on 'messy' technical replicates, e.g. >2 full CT values apart. #does not make a big difference
#calpro_filt$CT2_G <- as.numeric(calpro_filt$CT2_G)
#calpro_filt$CT_flag_G <- ifelse(abs(calpro_filt$CT2_G - calpro_filt$CT1_G)>3, yes="FLAG", no="ok")
#calpro_filt$CT_flag_S <- ifelse(abs(calpro_filt$CT2_S - calpro_filt$CT1_S)>3, yes="FLAG", no="ok")

#calpro_filt2 <- calpro_filt %>% filter(CT_flag_G!="FLAG"&CT_flag_S!="FLAG")
#dim(calpro_filt2) #n=256 samples now

#associate with meta
calpro_meta <- full_join(calpro_filt, meta_seq) %>% filter(!is.na(FoldChange) & !is.na(Participant_ID))
length(calpro_meta$SampleID) #281 valid samples #now 329 #or 319, etc. based on filtering
dplyr::count(calpro_meta, Participant_ID) #from 47 people #now 95 #or 94 etc. based on filtering
length(as.data.frame(dplyr::count(calpro_meta, Participant_ID))$n) #n=136 participants now

#make summaries before and after vaccine
calpro_summary <- calpro_meta %>% 
  group_by(Participant_ID, Stool_timing3, fever7d_aboveavg) %>%
  summarize(FoldChange=mean(FoldChange, na.rm=TRUE))
calpro_summary

#make overall summary #but also by Batch so we can check
calpro_summary1 <- calpro_meta %>% 
  group_by(Participant_ID, fever7d_aboveavg, cDNA_Batch) %>%
  summarize(FoldChange=mean(FoldChange, na.rm=TRUE))
calpro_summary1

#UPDATED: with extra plates 4-5: plot and test the sample 3's only.
calpro_3 <- calpro_meta %>% filter(sample_no==3) #no joining with ELISA data. Avoid confusion.
dim(calpro_3) #95 people as expected #updated: n=134 #now: n=145

#pdf(width=3, height=3, "/ebio/abt3_projects2/uHEAT/data/plots4/Calpro_fever7d_plus96.pdf")
p <- ggplot(calpro_3, aes(x=fever7d_aboveavg, y=log(FoldChange), colour=fever7d_aboveavg)) +
  geom_boxplot(outlier.shape=NA) +
  geom_jitter(width=0.1, height=0) +
    scale_colour_manual(values=c("grey60", "firebrick3")) +
  annotate('segment', x=1, xend=2, y=7.5, yend=7.5) +
  annotate('text', x=1.5, y=8, label=c("p=0.16")) +
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
               panel.background = element_blank(), axis.line = element_line(colour = "black"),
               axis.title.y = element_text(margin = margin(r = 10))) +
  ylab("Fecal Calprotectin (Log Fold Change)") + xlab("Fever") + theme(legend.position = "none") +
  ggtitle("Sample #3 - qPCR (+96 samples)")
p
#dev.off()
wilcox.test(calpro_3$FoldChange ~ calpro_3$fever7d_aboveavg) #NS, p=0.5 #or p=0.39 #updated, and with no-GAPDH-detection excluded: p=0.06
#shoot, we've gone back to p=0.15

#considering only the exact same samples we have for elisa?
calpro_3_filt <- calpro_3 %>% filter(Participant_ID %in% lc$Participant_ID)
dim(calpro_3) #145 people
dim(calpro_3_filt) #127 people

#pdf(width=3, height=3, "/ebio/abt3_projects2/uHEAT/data/plots4/Calpro_fever7d_plus96.pdf")
p <- ggplot(calpro_3_filt, aes(x=fever7d_aboveavg, y=log(FoldChange), colour=fever7d_aboveavg)) +
  geom_boxplot(outlier.shape=NA) +
  geom_jitter(width=0.1, height=0) +
    scale_colour_manual(values=c("grey60", "firebrick3")) +
  annotate('segment', x=1, xend=2, y=7.5, yend=7.5) +
  annotate('text', x=1.5, y=8, label=c("p=0.06")) +
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
               panel.background = element_blank(), axis.line = element_line(colour = "black"),
               axis.title.y = element_text(margin = margin(r = 10))) +
  ylab("Fecal Calprotectin (Log Fold Change)") + xlab("Fever") + theme(legend.position = "none") +
  ggtitle("Sample #3 - qPCR (+96 samples)")
p
#dev.off()
wilcox.test(calpro_3_filt$FoldChange ~ calpro_3_filt$fever7d_aboveavg) #p=0.1, not a huge difference

summary(calpro_3$FoldChange) #exclude craaazy fold changes over 100 or less than 0.00000? (ie 10x highest quartile or 10x lowest)
calpro_3_filt <- calpro_3 %>% filter(!(FoldChange>100)&!(FoldChange<0.000001))
dim(calpro_3_filt) #n=137 people

#cairo_pdf(width=3, height=3, "/ebio/abt3_projects2/uHEAT/data/CleanPlots/Fig2E_Calpro_fever7d_qPCR.pdf")
p <- ggplot(calpro_3_filt, aes(x=fever7d_aboveavg, y=log(FoldChange), colour=fever7d_aboveavg)) +
  geom_boxplot(outlier.shape=NA) +
  geom_jitter(width=0.1, height=0) +
    scale_colour_manual(values=c("grey60", "firebrick3")) +
  annotate('segment', x=1, xend=2, y=7.2, yend=7.2) +
  annotate('text', x=1.5, y=8, label=c("p=0.08")) +
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
               panel.background = element_blank(), axis.line = element_line(colour = "black"),
               axis.title.y = element_text(margin = margin(r = 10))) +
  ylab("S100A9 (Log Fold Change)") + xlab("∆T") + theme(legend.position = "none") 
p
#dev.off()
wilcox.test(calpro_3_filt$FoldChange ~ calpro_3_filt$fever7d_aboveavg) #p=0.08 :) 


#overall test. by time.
calpro_summary$fever7d_aboveavg <- factor(calpro_summary$fever7d_aboveavg, levels=c("lo", "hi"))
calpro_summary$Stool_timing3 <- factor(calpro_summary$Stool_timing3, levels=c("before", "after"))

#pdf(width=4, height=3, "/ebio/abt3_projects2/uHEAT/data/plots4/Calpro_fever7d_beforeafter_plus48.pdf")
p <- ggplot(calpro_summary, aes(x=Stool_timing3, y=log(FoldChange), colour=fever7d_aboveavg)) +
  geom_boxplot(outlier.shape=NA) +
  geom_point(position=position_jitterdodge(jitter.width=0.1, jitter.height=0)) +
    scale_colour_manual(values=c("grey60", "firebrick3")) +
  theme_minimal()
p
#dev.off()

calpro_summary_before <- calpro_summary %>% filter(Stool_timing3=="before")
wilcox.test(calpro_summary_before$FoldChange~calpro_summary_before$fever7d_aboveavg) #p=0.5 #or p=0.3 #latest: p=0.1

#overall test. total.
calpro_summary1$fever7d_aboveavg <- factor(calpro_summary1$fever7d_aboveavg, levels=c("lo", "hi"))

#pdf(width=4, height=3, "/ebio/abt3_projects2/uHEAT/data/plots4/Calpro_fever7d_plus48.pdf")
p <- ggplot(calpro_summary1, aes(x=fever7d_aboveavg, y=log(FoldChange), colour=fever7d_aboveavg)) +
  geom_boxplot(outlier.shape=NA) +
  geom_point(position=position_jitterdodge(jitter.width=0.1, jitter.height=0)) +
    scale_colour_manual(values=c("grey60", "firebrick3")) +
  annotate('segment', x=1, xend=2, y=7.5, yend=7.5) +
  annotate('text', x=1.5, y=8, label=c("p=0.5")) +
  theme_minimal() +
  ggtitle("Avg Per Person - qPCR")
p
#dev.off()
wilcox.test(calpro_summary1$FoldChange ~ calpro_summary1$fever7d_aboveavg) #NS, p=0.46, but trend is better
#latest: p=0.1

#check over time.
#don't take all the sample 3's for this one, i.e. only participants with more than one time point
pdata <- calpro_meta %>% filter(!(cDNA_Batch %in% c("4", "5", "6")))

#plot all
#cairo_pdf(width=4, height=3, "/ebio/abt3_projects2/uHEAT/data/CleanPlots/3I_Calpro_Time01.pdf")
p <- ggplot(pdata, aes(x=Time01, y=log(FoldChange), colour=fever7d_aboveavg)) + 
  #geom_point() + 
  geom_line(aes(group=Participant_ID), alpha=0.3) +
  geom_smooth(method='loess', fill='white', alpha=0.7) + 
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
               panel.background = element_blank(), axis.line = element_line(colour = "black"),
               axis.title.y = element_text(margin = margin(r = 10))) + 
  xlab("Time (days)") + ylab("Log Fold Change") + 
  ggtitle("S100A9") + labs(colour="∆T") + 
  scale_x_continuous(breaks = (seq(-7, 7, by = 7))) + 
  scale_colour_manual(values=c("grey50", "firebrick3")) +
  annotate('segment', x=0, xend=0, y=-3, yend=6, linetype='dashed')
p
#dev.off()

#test statistically via mixed linear model #the same way as for beta diversity 
m1 <- lme(FoldChange ~ seq_depth +  Bristol_Stool_Score2 + Time01 + fever7d_aboveavg + Time01*fever7d_aboveavg, random=~1|Participant_ID, data = calpro_meta, 
            na.action=na.exclude, method="ML")
summary(m1) #NS

#by boxplot.
#pdf(width=4, height=3, "/ebio/abt3_projects2/uHEAT/data/plots4/Calpro_sampleno.pdf")
p <- ggplot(calpro_meta, aes(x=as.factor(sample_no), y=log(FoldChange), colour=fever7d_aboveavg)) + 
  geom_boxplot(outlier.shape=NA) + 
  geom_point(position=position_jitterdodge(jitter.width=0.1, jitter.height = 0)) + 
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
               panel.background = element_blank(), axis.line = element_line(colour = "black"),
               axis.title.y = element_text(margin = margin(r = 10))) + 
  xlab("Sample") + ylab("Log Fold Change") + 
  ggtitle("S100A9") + labs(colour="Fever") + 
  scale_colour_manual(values=c("grey60", "firebrick3")) +
  annotate('segment', x=0, xend=0, y=-3, yend=6, linetype='dashed')
p
#dev.off()


#and sanity check, has it gotten MORE significant with the extra samples? or less?
calpro_3a <- calpro_3 %>% filter(!cDNA_Batch%in%c("6"))
#pdf(width=3, height=3, "/ebio/abt3_projects2/uHEAT/data/plots4/Calpro_fever7d_plus48.pdf")
p <- ggplot(calpro_3a, aes(x=fever7d_aboveavg, y=log(FoldChange), colour=fever7d_aboveavg)) +
  geom_boxplot(outlier.shape=NA) +
  geom_jitter(width=0.1, height=0) +
    scale_colour_manual(values=c("grey60", "firebrick3")) +
  annotate('segment', x=1, xend=2, y=7.5, yend=7.5) +
  annotate('text', x=1.5, y=8, label=c("p=0.4")) +
  theme_minimal() +
  ggtitle("Sample #3 - qPCR (+48 samples)")
p
#dev.off()
wilcox.test(calpro_3a$FoldChange ~ calpro_3a$fever7d_aboveavg) #NS, p=0.4 #ok it did get a bit more significant
#without the last samples it is p=0.06 :(


#check correlation with real ELISA data, overall and by sampleID / time / batch / etc.
calpro_lc <- full_join(calpro_summary1, lc)
#pdf(width=3, height=3, "/ebio/abt3_projects2/uHEAT/data/plots4/Calpro_qPCR_vs_ELISA_plus48.pdf")
p <- ggplot(calpro_lc, aes(x=log(Calpro.pg.mL), y=log(FoldChange))) + geom_point() + 
  geom_smooth(method='lm') +
  theme_minimal() +
  annotate('text', x=6, y=-2.5, label=c("p=0.005\nrho=0.33")) +
  ggtitle("Endpoint ELISA vs Avg. qPCR")
p
#dev.off()
cor.test(calpro_lc$Calpro.pg.mL, calpro_lc$FoldChange, method='spearman') #p=0.005, rho=0.33
#updated, it's WORSE: p=0.03, rho=0.2 (but I've included a lot of 'before' samples, to be fair)
#now we are at: p=0.01, rho=0.2

#do the before / after samples correlate better?
calpro_lc2 <- full_join(calpro_summary, lc)
p <- ggplot(calpro_lc2[which(calpro_lc2$Stool_timing3=="before"),], aes(x=Calpro.pg.mL, y=log(FoldChange))) + geom_point() + 
  geom_smooth(method='lm')
p
cor.test(calpro_lc2[which(calpro_lc2$Stool_timing3=="before"),]$Calpro.pg.mL, calpro_lc2[which(calpro_lc2$Stool_timing3=="before"),]$FoldChange, method='spearman') #p=0.07, rho=0.27
#new normalization: p=0.1, rho=0.22 #new new : p=0.05, rho=0.16
p <- ggplot(calpro_lc2[which(calpro_lc2$Stool_timing3=="after"),], aes(x=Calpro.pg.mL, y=log(FoldChange))) + geom_point() + 
  geom_smooth(method='lm')
p
cor.test(calpro_lc2[which(calpro_lc2$Stool_timing3=="after"),]$Calpro.pg.mL, calpro_lc2[which(calpro_lc2$Stool_timing3=="after"),]$FoldChange, method='spearman') #p=0.01, rho=0.38

#does any individual BATCH correlate better?
calpro_lc3 <- full_join(calpro_meta, lc)
calpro_lc_batch1 <- calpro_lc3 %>% filter(cDNA_Batch==1)
calpro_lc_batch2 <- calpro_lc3 %>% filter(cDNA_Batch==2)
calpro_lc_batch3 <- calpro_lc3 %>% filter(cDNA_Batch==3)
calpro_lc_batch4 <- calpro_lc3 %>% filter(cDNA_Batch==4)
calpro_lc_batch5 <- calpro_lc3 %>% filter(cDNA_Batch==5)
p <- ggplot(calpro_lc_batch1, aes(x=Calpro.pg.mL, y=log(FoldChange))) + geom_point() + 
  geom_smooth(method='lm')
p #poorly correlates
p <- ggplot(calpro_lc_batch2, aes(x=Calpro.pg.mL, y=log(FoldChange))) + geom_point() + 
  geom_smooth(method='lm')
p #batch 2 does not
p <- ggplot(calpro_lc_batch3, aes(x=Calpro.pg.mL, y=log(FoldChange))) + geom_point() + 
  geom_smooth(method='lm')
p #batch 3 does ish
p <- ggplot(calpro_lc_batch4, aes(x=Calpro.pg.mL, y=log(FoldChange))) + geom_point() + 
  geom_smooth(method='lm')
p #batch 4 does not at all
p <- ggplot(calpro_lc_batch5, aes(x=Calpro.pg.mL, y=log(FoldChange))) + geom_point() + 
  geom_smooth(method='lm')
p #batch 5 does ish

#do any individual sample #s correlate better?

calpro_lc2_1 <- calpro_lc3 %>% filter(sample_no==1)
calpro_lc2_2 <- calpro_lc3 %>% filter(sample_no==2)
calpro_lc2_3 <- calpro_lc3 %>% filter(sample_no==3)
calpro_lc2_4 <- calpro_lc3 %>% filter(sample_no==4)
calpro_lc2_5 <- calpro_lc3 %>% filter(sample_no==5)
calpro_lc2_6 <- calpro_lc3 %>% filter(sample_no==6)

p <- ggplot(calpro_lc2_1, aes(x=Calpro.pg.mL, y=log(FoldChange))) + geom_point() + 
  geom_smooth(method='lm')
cor.test(calpro_lc2_1$Calpro.pg.mL, calpro_lc2_1$FoldChange, method='spearman') #rho=0.14, p=0.3
wilcox.test(calpro_lc2_1$Calpro.pg.mL ~ calpro_lc2_1$fever7d_aboveavg) #p=0.8
p <- ggplot(calpro_lc2_2, aes(x=Calpro.pg.mL, y=log(FoldChange))) + geom_point() + 
  geom_smooth(method='lm')
cor.test(calpro_lc2_2$Calpro.pg.mL, calpro_lc2_2$FoldChange, method='spearman') #rho=0.04, p=0.8
wilcox.test(calpro_lc2_2$Calpro.pg.mL ~ calpro_lc2_2$fever7d_aboveavg) #p=0.7
p <- ggplot(calpro_lc2_3, aes(x=Calpro.pg.mL, y=log(FoldChange))) + geom_point() + 
  geom_smooth(method='lm')
cor.test(calpro_lc2_3$Calpro.pg.mL, calpro_lc2_3$FoldChange, method='spearman') #rho=0.24, p=0.12 #updated: p=0.05
wilcox.test(calpro_lc2_3$Calpro.pg.mL ~ calpro_lc2_3$fever7d_aboveavg) #p=0.01 by the endpoint ELISA
wilcox.test(calpro_lc2_3$FoldChange ~ calpro_lc2_3$fever7d_aboveavg)  #p=0.2 by the qPCR
#updated it seems so close - p=0.1 - why is it almost significant here, but not above????
p <- ggplot(calpro_lc2_3, aes(x=fever7d_aboveavg, y=log(FoldChange))) + geom_boxplot() +
  geom_jitter(width=0.1, height=0)
p
duplicated(calpro_lc2_3$Participant_ID) #none are duplicated
dim(calpro_lc2_3) #only 84 samples; some have gotten lost?
setdiff(calpro_lc2_3$Participant_ID, calpro_meta$Participant_ID)
setdiff(calpro_meta$Participant_ID, calpro_lc2_3$Participant_ID) #right, so, 5 RNA-people didn't have fresh samples (?)

p <- ggplot(calpro_lc2_4, aes(x=Calpro.pg.mL, y=log(FoldChange))) + geom_point() + 
  geom_smooth(method='lm')
cor.test(calpro_lc2_4$Calpro.pg.mL, calpro_lc2_4$FoldChange, method='spearman') #rho=0.20, p=0.18
wilcox.test(calpro_lc2_4$Calpro.pg.mL ~ calpro_lc2_4$fever7d_aboveavg) #p=0.7
p <- ggplot(calpro_lc2_5, aes(x=Calpro.pg.mL, y=log(FoldChange))) + geom_point() + 
  geom_smooth(method='lm')
cor.test(calpro_lc2_5$Calpro.pg.mL, calpro_lc2_5$FoldChange, method='spearman') #rho=0.33, p=0.03
wilcox.test(calpro_lc2_5$Calpro.pg.mL ~ calpro_lc2_5$fever7d_aboveavg) #p=0.7
#pdf(width=3, height=3, "/ebio/abt3_projects2/uHEAT/data/plots4/Calpro_qPCRs6_vs_ELISA.pdf")
p <- ggplot(calpro_lc2_6, aes(x=log(Calpro.pg.mL), y=log(FoldChange))) + geom_point() + 
  geom_smooth(method='lm') +
  theme_minimal() +
  annotate('text', x=6, y=2.5, label=c("p=0.005\nrho=0.42")) +
  ggtitle("Endpoint ELISA vs End. qPCR")
p
#dev.off()
cor.test(calpro_lc2_6$Calpro.pg.mL, calpro_lc2_6$FoldChange, method='spearman') #rho=0.41, p=0.005
wilcox.test(calpro_lc2_6$Calpro.pg.mL ~ calpro_lc2_6$fever7d_aboveavg) #p=0.7
#so it definitely starts to correlate better towards the end - but temporally that's also kind of fair. right?
#also with the re-normalization, sample #6 is still the best at p=0.005, rho=0.4

p <- ggplot(calpro_lc2_6, aes(x=fever7d_aboveavg, y=log(FoldChange))) + geom_boxplot(outlier.shape=NA) + geom_jitter(width=0.1, height=0)
wilcox.test(calpro_lc2_6$FoldChange~calpro_lc2_6$fever7d_aboveavg) #NS, p=0.4... but it looks a lot closer...

p <- ggplot(calpro_lc2_3, aes(x=fever7d_aboveavg, y=log(FoldChange))) + geom_boxplot(outlier.shape=NA) + geom_jitter(width=0.1, height=0)
wilcox.test(calpro_lc2_3$FoldChange~calpro_lc2_3$fever7d_aboveavg) #NS, p=0.5... no trend...

#plot samples 3 & 6, only.
pdata <- full_join(calpro_lc2_3, calpro_lc2_6)
#pdf(width=4, height=3, "/ebio/abt3_projects2/uHEAT/data/plots4/Calpro_fever7d_3vs6.pdf")
p <- ggplot(pdata, aes(x=as.factor(sample_no), y=log(FoldChange), colour=fever7d_aboveavg)) +
  geom_boxplot(outlier.shape=NA) +
  geom_point(position=position_jitterdodge(jitter.width=0.1, jitter.height=0)) +
    scale_colour_manual(values=c("grey60", "firebrick3")) +
  theme_minimal() + 
  xlab("Sample ID")
p
#dev.off()
wilcox.test(calpro_lc2_3$FoldChange ~ calpro_lc2_3$fever7d_aboveavg)  #p=0.2 by the qPCR
wilcox.test(calpro_lc2_6$FoldChange ~ calpro_lc2_6$fever7d_aboveavg)  #p=0.5 by the qPCR

#what does the ELISA data look like for the subset that I chose?
lc_subset <- lc_meta %>% filter(Participant_ID %in% calpro_summary1$Participant_ID)
#pdf(width=4, height=3, "/ebio/abt3_projects2/uHEAT/data/plots4/Calpro_fever7d_ELISA_fromqPCRsubset.pdf")
p <- ggplot(lc_subset, aes(x=fever7d_aboveavg, y=log(Calpro.pg.mL), colour=fever7d_aboveavg)) +
  geom_boxplot(outlier.shape=NA) +
  geom_point(position=position_jitterdodge(jitter.width=0.1, jitter.height=0)) +
    scale_colour_manual(values=c("grey60", "firebrick3")) +
  annotate('segment', x=1, xend=2, y=12.5, yend=12.5) +
  annotate('text', x=1.5, y=13, label=c("p=0.7")) +
  theme_minimal() +
  ggtitle("Endpoint Per Person - ELISA")
p
#dev.off()
wilcox.test(lc_subset$Calpro.pg.mL ~ lc_subset$fever7d_aboveavg) 
#very significant, of course.

#can we quantify stability over time - e.g. how well before/after correlate?
calpro_summary2 <- calpro_summary %>% pivot_wider(names_from=Stool_timing3, values_from=FoldChange)
p <- ggplot(calpro_summary2, aes(x=log(before), y=log(after))) + geom_point() + geom_smooth(method='lm')
p
cor.test(calpro_summary2$before, calpro_summary2$after, method='spearman') #p=0.08, rho=0.25
#with the new normalization, p=0.5, rho=0.09...

#does the average INCREASE in calpro associate with fever? #No :) 
calpro_summary2$FoldChange_Time <- calpro_summary2$after / calpro_summary2$before
#pdf(width=4, height=3, "/ebio/abt3_projects2/uHEAT/data/plots4/Calpro_fever7d_beforeafterfoldchange.pdf")
p <- ggplot(calpro_summary2, aes(x=fever7d_aboveavg, y=log(FoldChange_Time), colour=fever7d_aboveavg)) + geom_boxplot(outlier.shape=NA) +
  geom_jitter(width=0.1, height=0) +
    scale_colour_manual(values=c("grey60", "firebrick3")) +
  theme_minimal() +
  annotate('segment', x=1, xend=2, y=5, yend=5) + 
  annotate('text', x=1.5, y=5.5, label=c("p=0.6")) + 
  ggtitle("Fold-Change Increase After vs. Before")
p
#dev.off()
wilcox.test(calpro_summary2$FoldChange_Time ~ calpro_summary2$fever7d_aboveavg)

#is there a way to calculate distance over time...?

#supposing I added another 96 samples, i.e. another 16 people. 
#who is left that I haven't tested yet.
lc_left <- lc_meta %>% filter(!(Participant_ID %in% calpro_meta$Participant_ID)&!is.na(fever7d_aboveavg)&!is.na(Calpro.pg.g))
dim(lc_left) #there are only 22 more samples left to test! (based on ELISA)
#and, in the whole study?
lc_left <- meta %>% filter(!(Participant_ID %in% calpro_meta$Participant_ID)&!is.na(fever7d_aboveavg))
dim(lc_left) #there are 35 samples left in the whole study - very doable

p <- ggplot(lc_left, aes(x=fever7d_aboveavg, y=log(Calpro.pg.g), colour=fever7d_aboveavg)) + geom_boxplot(outlier.shape=NA) +
  geom_jitter(width=0.1, height=0) +
    scale_colour_manual(values=c("grey60", "firebrick3")) +
  theme_minimal()
p
wilcox.test(lc_left$Calpro.pg.g~lc_left$fever7d_aboveavg)

lc_left <- lc_left %>% dplyr::select(Participant_ID, Calpro.pg.g, fever7d_aboveavg)
lc_left <- lc_left[order(lc_left$Calpro.pg.g, decreasing=TRUE),]
head(lc_left[which(lc_left$fever7d_aboveavg=="hi"),], 8)
tail(lc_left[which(lc_left$fever7d_aboveavg=="lo"),], 8)

#supposing I just took those 16 samples, is it enough for significance?
lc_test_subset <- Reduce(full_join, list(lc_subset, 
                                         head(lc_left, 24), 
                                         tail(lc_left, 24)))
dim(lc_subset)
dim(lc_test_subset)

#pdf(width=4, height=3, "/ebio/abt3_projects2/uHEAT/data/plots4/Calpro_ELISA_subset2.pdf")
p <- ggplot(lc_test_subset, aes(x=fever7d_aboveavg, y=log(Calpro.pg.g), colour=fever7d_aboveavg)) + geom_boxplot(outlier.shape=NA) +
  geom_jitter(width=0.1, height=0) +
    scale_colour_manual(values=c("grey60", "firebrick3")) +
  theme_minimal() + 
  ggtitle("Hypothetical Subset N=95")
p
#dev.off()
wilcox.test(lc_test_subset$Calpro.pg.g~lc_test_subset$fever7d_aboveavg) #now it's significant.

#VERSUS what if I do one before and one after sample (e.g. sample 6 and sample 3)? then I could easily add 48 more people

#export the lc_subset so I can find the samples after
export_me <- full_join(head(lc_left, 24), tail(lc_left, 24))
#write.csv(export_me, "/ebio/abt3_projects2/uHEAT/data/metadata/calpro_qPCRsamples_todo_set3.csv")

#supposing I just did ALL the rest, calpro ELISA data or no calpro ELISA data?
all_left <- meta %>% filter(!(Participant_ID %in% calpro_meta$Participant_ID)&!is.na(fever7d_aboveavg))
dim(all_left) #there are 82 people in total left #update: 35
write.csv(all_left$Participant_ID, "/ebio/abt3_projects2/uHEAT/data/metadata/calpro_qPCRsamples_todo_set4.csv")

```

